INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(1, 'test1',  'aa');
INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(2, 'test2', 'baa');
INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(3, 'test3', 'maa');
INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(4, 'test4', 'gaa');